package ch.ehi.ili2ofgdb.jdbc;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * Parses and evaluates the small SQL dialect that ili2db issues against the JDBC driver.
 *
 * <p>Only the statements generated by ili2db and its DDL generator are supported: {@code CREATE
 * TABLE}, {@code INSERT}, {@code UPDATE}, {@code DELETE} and the WHERE conditions used by SELECT
 * emulation.
 */
public final class OfgdbSql {

    /** Marker used by {@link OfgdbStatement#encodeLiteral(Object)} for binary values. */
    public static final String BYTE_LITERAL_PREFIX = "__OFGDB_BYTES_B64__:";

    private OfgdbSql() {
    }

    // ------------------------------------------------------------------
    // Literals
    // ------------------------------------------------------------------

    /** Encodes a JDBC value as SQL literal, exactly like the statement implementation used to. */
    public static String encodeLiteral(Object value) {
        if (value == null) {
            return "NULL";
        }
        if (value instanceof Number) {
            return value.toString();
        }
        if (value instanceof Boolean) {
            return ((Boolean) value).booleanValue() ? "1" : "0";
        }
        if (value instanceof java.sql.Time) {
            return "'1970-01-01 " + value.toString() + "'";
        }
        if (value instanceof java.sql.Timestamp) {
            return "'" + value.toString().replace('T', ' ') + "'";
        }
        if (value instanceof java.sql.Date) {
            return "'" + value.toString() + "'";
        }
        if (value instanceof byte[]) {
            return "'" + BYTE_LITERAL_PREFIX
                    + java.util.Base64.getEncoder().encodeToString((byte[]) value) + "'";
        }
        String text = value.toString().replace("'", "''");
        return "'" + text + "'";
    }

    /** Parses a literal returned by the file geodatabase into the value model of the driver. */
    static Object parseValue(String value) {
        if (value == null) {
            return null;
        }
        String trimmed = value.trim();
        if (trimmed.isEmpty()) {
            return "";
        }
        if (trimmed.matches("-?\\d+")) {
            try {
                return Integer.valueOf(trimmed);
            } catch (NumberFormatException ignore) {
            }
            try {
                return Long.valueOf(trimmed);
            } catch (NumberFormatException ignore) {
            }
        }
        if (trimmed.matches("-?\\d+\\.\\d+")) {
            try {
                return new BigDecimal(trimmed);
            } catch (NumberFormatException ignore) {
            }
        }
        if (trimmed.startsWith(BYTE_LITERAL_PREFIX)) {
            String b64 = trimmed.substring(BYTE_LITERAL_PREFIX.length());
            try {
                return java.util.Base64.getDecoder().decode(b64);
            } catch (IllegalArgumentException ignore) {
                return value;
            }
        }
        return value;
    }

    /**
     * Parses a SQL literal from a statement that was already materialized by the prepared
     * statement implementation.
     */
    static Object literal(String text) {
        if (text == null) {
            return null;
        }
        String value = text.trim();
        if (value.length() == 0 || "NULL".equalsIgnoreCase(value)) {
            return null;
        }
        if (value.charAt(0) == '\'' && value.length() >= 2) {
            String inner = value.substring(1, value.length() - 1).replace("''", "'");
            return parseValue(inner);
        }
        Object parsed = parseValue(value);
        return parsed;
    }

    // ------------------------------------------------------------------
    // WHERE
    // ------------------------------------------------------------------

    /** Parsed WHERE condition. */
    public static final class Where {
        private final Node root;

        private Where(Node root) {
            this.root = root;
        }

        public static Where parse(String sql) {
            WhereParser parser = new WhereParser(sql);
            Node node = parser.parseCondition();
            parser.expectEnd();
            return new Where(node);
        }

        public boolean matches(Map<String, Object> row) {
            return root.matches(row);
        }
    }

    private interface Node {
        boolean matches(Map<String, Object> row);
    }

    private static final class AndNode implements Node {
        private final Node left;
        private final Node right;

        private AndNode(Node left, Node right) {
            this.left = left;
            this.right = right;
        }

        @Override
        public boolean matches(Map<String, Object> row) {
            return left.matches(row) && right.matches(row);
        }
    }

    private static final class OrNode implements Node {
        private final Node left;
        private final Node right;

        private OrNode(Node left, Node right) {
            this.left = left;
            this.right = right;
        }

        @Override
        public boolean matches(Map<String, Object> row) {
            return left.matches(row) || right.matches(row);
        }
    }

    private static final class NotNode implements Node {
        private final Node inner;

        private NotNode(Node inner) {
            this.inner = inner;
        }

        @Override
        public boolean matches(Map<String, Object> row) {
            return !inner.matches(row);
        }
    }

    private static final class IsNullNode implements Node {
        private final String column;
        private final boolean negated;

        private IsNullNode(String column, boolean negated) {
            this.column = column;
            this.negated = negated;
        }

        @Override
        public boolean matches(Map<String, Object> row) {
            Object actual = rowValue(row, column);
            return negated ? actual != null : actual == null;
        }
    }

    private static final class ComparisonNode implements Node {
        private final String column;
        private final String operator;
        private final Object expected;

        private ComparisonNode(String column, String operator, Object expected) {
            this.column = column;
            this.operator = operator;
            this.expected = expected;
        }

        @Override
        public boolean matches(Map<String, Object> row) {
            Object actual = rowValue(row, column);
            if (actual == null || expected == null) {
                return false;
            }
            int cmp = compareValues(actual, expected);
            if ("=".equals(operator) || "==".equals(operator)) {
                return cmp == 0;
            }
            if ("<>".equals(operator) || "!=".equals(operator)) {
                return cmp != 0;
            }
            if ("<".equals(operator)) {
                return cmp < 0;
            }
            if (">".equals(operator)) {
                return cmp > 0;
            }
            if ("<=".equals(operator)) {
                return cmp <= 0;
            }
            if (">=".equals(operator)) {
                return cmp >= 0;
            }
            return false;
        }
    }

    private static final class InNode implements Node {
        private final String column;
        private final List<Object> values;
        private final boolean negated;

        private InNode(String column, List<Object> values, boolean negated) {
            this.column = column;
            this.values = values;
            this.negated = negated;
        }

        @Override
        public boolean matches(Map<String, Object> row) {
            Object actual = rowValue(row, column);
            boolean found = false;
            if (actual != null) {
                for (Object candidate : values) {
                    if (candidate != null && compareValues(actual, candidate) == 0) {
                        found = true;
                        break;
                    }
                }
            }
            return negated ? !found : found;
        }
    }

    private static final class WhereParser {
        private final String sql;
        private int position;

        private WhereParser(String sql) {
            this.sql = sql != null ? sql : "";
        }

        private Node parseCondition() {
            Node left = parseAnd();
            while (matchKeyword("OR")) {
                left = new OrNode(left, parseAnd());
            }
            return left;
        }

        private Node parseAnd() {
            Node left = parseNot();
            while (matchKeyword("AND")) {
                left = new AndNode(left, parseNot());
            }
            return left;
        }

        private Node parseNot() {
            if (matchKeyword("NOT")) {
                return new NotNode(parseNot());
            }
            return parsePrimary();
        }

        private Node parsePrimary() {
            skipWhitespace();
            if (peek() == '(') {
                position++;
                Node inner = parseCondition();
                skipWhitespace();
                if (peek() != ')') {
                    throw error("missing closing parenthesis");
                }
                position++;
                return inner;
            }
            String column = parseOperand();
            skipWhitespace();
            String upper = remainingUpper();
            if (upper.startsWith("IS")) {
                position += 2;
                boolean negated = matchKeyword("NOT");
                if (!matchKeyword("NULL")) {
                    throw error("expected NULL after IS");
                }
                return new IsNullNode(column, negated);
            }
            boolean negated = false;
            if (upper.startsWith("NOT")) {
                int save = position;
                position += 3;
                if (matchKeyword("IN")) {
                    negated = true;
                } else {
                    position = save;
                }
            }
            if (matchKeyword("IN")) {
                skipWhitespace();
                if (peek() != '(') {
                    throw error("expected ( after IN");
                }
                position++;
                List<Object> values = new ArrayList<Object>();
                while (true) {
                    skipWhitespace();
                    if (peek() == ')') {
                        position++;
                        break;
                    }
                    values.add(parseLiteralToken());
                    skipWhitespace();
                    if (peek() == ',') {
                        position++;
                        continue;
                    }
                    if (peek() == ')') {
                        position++;
                        break;
                    }
                    throw error("unexpected token in IN list");
                }
                return new InNode(column, values, negated);
            }
            String operator = parseOperator();
            Object expected = parseLiteralToken();
            return new ComparisonNode(column, operator, expected);
        }

        private String parseOperand() {
            skipWhitespace();
            char c = peek();
            if (c == '\'' || Character.isDigit(c) || c == '-' || c == '+') {
                throw error("expected column reference");
            }
            String name = parseIdentifier();
            skipWhitespace();
            while (peek() == '.') {
                position++;
                name = parseIdentifier();
                skipWhitespace();
            }
            return unquote(name);
        }

        private String parseIdentifier() {
            StringBuilder out = new StringBuilder();
            if (peek() == '"') {
                position++;
                while (position < sql.length() && sql.charAt(position) != '"') {
                    out.append(sql.charAt(position++));
                }
                if (position < sql.length()) {
                    position++;
                }
                return out.toString();
            }
            while (position < sql.length()) {
                char c = sql.charAt(position);
                if (Character.isLetterOrDigit(c) || c == '_' || c == '$' || c == '#') {
                    out.append(c);
                    position++;
                } else {
                    break;
                }
            }
            if (out.length() == 0) {
                throw error("expected identifier");
            }
            return out.toString();
        }

        private Object parseLiteralToken() {
            skipWhitespace();
            char c = peek();
            if (c == '\'') {
                StringBuilder out = new StringBuilder();
                out.append(c);
                position++;
                while (position < sql.length()) {
                    char current = sql.charAt(position);
                    out.append(current);
                    position++;
                    if (current == '\'') {
                        if (position < sql.length() && sql.charAt(position) == '\'') {
                            out.append(sql.charAt(position));
                            position++;
                            continue;
                        }
                        break;
                    }
                }
                return literal(out.toString());
            }
            StringBuilder out = new StringBuilder();
            while (position < sql.length()) {
                char current = sql.charAt(position);
                if (Character.isLetterOrDigit(current) || current == '.' || current == '-'
                        || current == '+' || current == '_') {
                    out.append(current);
                    position++;
                } else {
                    break;
                }
            }
            if (out.length() == 0) {
                throw error("expected literal");
            }
            return literal(out.toString());
        }

        private String parseOperator() {
            skipWhitespace();
            String remaining = sql.substring(position);
            String[] operators = { "<>", "!=", "<=", ">=", "=", "<", ">" };
            for (String operator : operators) {
                if (remaining.startsWith(operator)) {
                    position += operator.length();
                    return operator;
                }
            }
            throw error("expected comparison operator");
        }

        private void skipWhitespace() {
            while (position < sql.length() && Character.isWhitespace(sql.charAt(position))) {
                position++;
            }
        }

        private char peek() {
            return position < sql.length() ? sql.charAt(position) : '\0';
        }

        private String remainingUpper() {
            return sql.substring(position).toUpperCase(Locale.ROOT);
        }

        private boolean matchKeyword(String keyword) {
            skipWhitespace();
            String remaining = sql.substring(position);
            if (remaining.length() < keyword.length()) {
                return false;
            }
            if (!remaining.regionMatches(true, 0, keyword, 0, keyword.length())) {
                return false;
            }
            int end = position + keyword.length();
            if (end < sql.length()) {
                char next = sql.charAt(end);
                if (Character.isLetterOrDigit(next) || next == '_') {
                    return false;
                }
            }
            position = end;
            return true;
        }

        private IllegalStateException error(String message) {
            return new IllegalStateException(message + " in WHERE clause <" + sql + ">");
        }

        private void expectEnd() {
            skipWhitespace();
            if (position < sql.length()) {
                throw error("unexpected trailing input");
            }
        }
    }

    private static Object rowValue(Map<String, Object> row, String column) {
        if (row == null || column == null) {
            return null;
        }
        Object direct = row.get(column);
        if (direct != null || row.containsKey(column)) {
            return direct;
        }
        String probe = unquote(column);
        for (Map.Entry<String, Object> entry : row.entrySet()) {
            if (entry.getKey().equalsIgnoreCase(probe)) {
                return entry.getValue();
            }
        }
        return null;
    }

    private static int compareValues(Object left, Object right) {
        BigDecimal leftNumber = asNumber(left);
        BigDecimal rightNumber = asNumber(right);
        if (leftNumber != null && rightNumber != null) {
            return leftNumber.compareTo(rightNumber);
        }
        String leftString = left instanceof byte[] ? base64((byte[]) left) : left.toString();
        String rightString = right instanceof byte[] ? base64((byte[]) right) : right.toString();
        return leftString.compareTo(rightString);
    }

    private static BigDecimal asNumber(Object value) {
        if (value instanceof BigDecimal) {
            return (BigDecimal) value;
        }
        if (value instanceof Number) {
            return new BigDecimal(value.toString());
        }
        if (value instanceof String) {
            try {
                return new BigDecimal(((String) value).trim());
            } catch (RuntimeException ignore) {
                return null;
            }
        }
        return null;
    }

    private static String base64(byte[] value) {
        return java.util.Base64.getEncoder().encodeToString(value);
    }

    private static String unquote(String value) {
        if (value == null) {
            return null;
        }
        String result = value.trim();
        if (result.length() >= 2 && result.charAt(0) == '"' && result.charAt(result.length() - 1) == '"') {
            result = result.substring(1, result.length() - 1);
        }
        return result;
    }

    // ------------------------------------------------------------------
    // Statement specs
    // ------------------------------------------------------------------

    public static final class ColumnSpec {
        public String name;
        public String type;
        public boolean primaryKey;
        public boolean notNull;
        public String geometryKind;
        public int srsId;
        public int dimension = 2;
        public int varcharLength = -1;
        public String domain;
        public boolean spatialIndex;
    }

    public static final class CreateTableSpec {
        public String tableName;
        public final List<ColumnSpec> columns = new ArrayList<ColumnSpec>();
    }

    public static final class InsertSpec {
        public String tableName;
        public final List<String> columns = new ArrayList<String>();
        public final List<Object> values = new ArrayList<Object>();
    }

    public static final class UpdateSpec {
        public String tableName;
        public final List<String> columns = new ArrayList<String>();
        public final List<Object> values = new ArrayList<Object>();
        public Where where;
    }

    public static final class DeleteSpec {
        public String tableName;
        public Where where;
    }

    /** Parses a {@code CREATE TABLE} statement produced by the DDL generator. */
    public static CreateTableSpec parseCreateTable(String sql) {
        String text = stripLeadingKeyword(sql, "CREATE TABLE");
        CreateTableSpec spec = new CreateTableSpec();
        int open = text.indexOf('(');
        if (open < 0) {
            throw new IllegalArgumentException("missing column list in <" + sql + ">");
        }
        spec.tableName = unquote(text.substring(0, open).trim());
        int close = matchingParen(text, open);
        String body = text.substring(open + 1, close);
        for (String columnText : splitTopLevel(body, ',')) {
            if (columnText.trim().isEmpty()) {
                continue;
            }
            spec.columns.add(parseColumn(columnText.trim()));
        }
        return spec;
    }

    private static ColumnSpec parseColumn(String text) {
        ColumnSpec column = new ColumnSpec();
        int position = 0;
        StringBuilder name = new StringBuilder();
        while (position < text.length()) {
            char c = text.charAt(position);
            if (Character.isWhitespace(c)) {
                break;
            }
            if (c == '"') {
                position++;
                while (position < text.length() && text.charAt(position) != '"') {
                    name.append(text.charAt(position++));
                }
                if (position < text.length()) {
                    position++;
                }
                continue;
            }
            name.append(c);
            position++;
        }
        column.name = name.toString();
        String remaining = text.substring(position).trim();
        String upper = remaining.toUpperCase(Locale.ROOT);
        column.primaryKey = upper.contains("PRIMARY KEY");
        column.notNull = upper.contains("NOT NULL") || column.primaryKey;
        int domainPos = upper.indexOf(" DOMAIN ");
        if (domainPos >= 0) {
            String domainText = remaining.substring(domainPos + " DOMAIN ".length()).trim();
            int end = 0;
            while (end < domainText.length()) {
                char c = domainText.charAt(end);
                if (Character.isLetterOrDigit(c) || c == '_' || c == '$' || c == '"') {
                    end++;
                } else {
                    break;
                }
            }
            column.domain = unquote(domainText.substring(0, end));
        }
        if (upper.startsWith("OFGDB_GEOMETRY")) {
            int open = remaining.indexOf('(');
            int close = remaining.indexOf(')', open);
            String[] parts = remaining.substring(open + 1, close).split(",");
            column.geometryKind = parts[0].trim().toUpperCase(Locale.ROOT);
            column.srsId = parts.length > 1 ? parseInt(parts[1].trim(), 0) : 0;
            column.dimension = parts.length > 2 ? parseInt(parts[2].trim(), 2) : 2;
            column.spatialIndex = parts.length > 3 && "INDEX".equalsIgnoreCase(parts[3].trim());
            column.type = "OFGDB_GEOMETRY";
        } else {
            int space = indexOfWhitespace(remaining);
            String type = space < 0 ? remaining : remaining.substring(0, space);
            int open = type.indexOf('(');
            if (open >= 0) {
                int close = type.indexOf(')', open);
                String argument = type.substring(open + 1, close);
                column.varcharLength = parseInt(argument.split(",")[0].trim(), -1);
                column.type = type.substring(0, open).toUpperCase(Locale.ROOT);
            } else {
                column.type = type.toUpperCase(Locale.ROOT);
            }
        }
        return column;
    }

    /** Parses an {@code INSERT INTO ... VALUES (...)} statement. */
    public static InsertSpec parseInsert(String sql) {
        String text = stripLeadingKeyword(sql, "INSERT INTO");
        InsertSpec spec = new InsertSpec();
        int valuesPos = indexOfKeyword(text, "VALUES");
        if (valuesPos < 0) {
            throw new IllegalArgumentException("missing VALUES in <" + sql + ">");
        }
        String head = text.substring(0, valuesPos).trim();
        String tail = text.substring(valuesPos + "VALUES".length()).trim();
        int open = head.indexOf('(');
        if (open >= 0) {
            int close = matchingParen(head, open);
            spec.tableName = unquote(head.substring(0, open).trim());
            for (String column : splitTopLevel(head.substring(open + 1, close), ',')) {
                spec.columns.add(unquote(column.trim()));
            }
        } else {
            spec.tableName = unquote(head);
        }
        if (tail.startsWith("(")) {
            int close = matchingParen(tail, 0);
            for (String value : splitTopLevel(tail.substring(1, close), ',')) {
                spec.values.add(literal(value.trim()));
            }
        }
        return spec;
    }

    /** Parses an {@code UPDATE ... SET ... [WHERE ...]} statement. */
    public static UpdateSpec parseUpdate(String sql) {
        String text = stripLeadingKeyword(sql, "UPDATE");
        UpdateSpec spec = new UpdateSpec();
        int setPos = indexOfKeyword(text, "SET");
        if (setPos < 0) {
            throw new IllegalArgumentException("missing SET in <" + sql + ">");
        }
        spec.tableName = unquote(text.substring(0, setPos).trim());
        String remaining = text.substring(setPos + "SET".length()).trim();
        int wherePos = indexOfKeyword(remaining, "WHERE");
        String assignments = wherePos < 0 ? remaining : remaining.substring(0, wherePos).trim();
        for (String assignment : splitTopLevel(assignments, ',')) {
            int equals = assignment.indexOf('=');
            if (equals < 0) {
                throw new IllegalArgumentException("invalid assignment in <" + sql + ">");
            }
            spec.columns.add(unquote(assignment.substring(0, equals).trim()));
            spec.values.add(literal(assignment.substring(equals + 1).trim()));
        }
        if (wherePos >= 0) {
            spec.where = Where.parse(remaining.substring(wherePos + "WHERE".length()).trim());
        }
        return spec;
    }

    /** Parses a {@code DELETE FROM ... [WHERE ...]} statement. */
    public static DeleteSpec parseDelete(String sql) {
        String text = stripLeadingKeyword(sql, "DELETE FROM");
        DeleteSpec spec = new DeleteSpec();
        int wherePos = indexOfKeyword(text, "WHERE");
        if (wherePos < 0) {
            spec.tableName = unquote(text.trim());
        } else {
            spec.tableName = unquote(text.substring(0, wherePos).trim());
            spec.where = Where.parse(text.substring(wherePos + "WHERE".length()).trim());
        }
        return spec;
    }

    // ------------------------------------------------------------------
    // Helpers
    // ------------------------------------------------------------------

    static List<String> splitTopLevel(String text, char delimiter) {
        List<String> parts = new ArrayList<String>();
        int depth = 0;
        boolean inString = false;
        int start = 0;
        for (int i = 0; i < text.length(); i++) {
            char c = text.charAt(i);
            if (inString) {
                if (c == '\'') {
                    if (i + 1 < text.length() && text.charAt(i + 1) == '\'') {
                        i++;
                    } else {
                        inString = false;
                    }
                }
                continue;
            }
            if (c == '\'') {
                inString = true;
            } else if (c == '(') {
                depth++;
            } else if (c == ')') {
                depth--;
            } else if (c == delimiter && depth == 0) {
                parts.add(text.substring(start, i));
                start = i + 1;
            }
        }
        parts.add(text.substring(start));
        return parts;
    }

    static boolean startsWithKeyword(String sql, String keyword) {
        if (sql == null) {
            return false;
        }
        String trimmed = sql.trim();
        if (trimmed.length() < keyword.length()) {
            return false;
        }
        if (!trimmed.regionMatches(true, 0, keyword, 0, keyword.length())) {
            return false;
        }
        int end = keyword.length();
        if (trimmed.length() > end) {
            char next = trimmed.charAt(end);
            if (Character.isLetterOrDigit(next) || next == '_') {
                return false;
            }
        }
        return true;
    }

    private static String stripLeadingKeyword(String sql, String keyword) {
        String trimmed = sql.trim();
        return trimmed.substring(keyword.length()).trim();
    }

    private static int indexOfKeyword(String text, String keyword) {
        String upper = text.toUpperCase(Locale.ROOT);
        int depth = 0;
        boolean inString = false;
        for (int i = 0; i < upper.length(); i++) {
            char c = upper.charAt(i);
            if (inString) {
                if (c == '\'') {
                    if (i + 1 < upper.length() && upper.charAt(i + 1) == '\'') {
                        i++;
                    } else {
                        inString = false;
                    }
                }
                continue;
            }
            if (c == '\'') {
                inString = true;
            } else if (c == '(') {
                depth++;
            } else if (c == ')') {
                depth--;
            } else if (depth == 0 && upper.startsWith(keyword, i)) {
                boolean before = i == 0 || !Character.isLetterOrDigit(upper.charAt(i - 1));
                int end = i + keyword.length();
                boolean after = end >= upper.length() || !Character.isLetterOrDigit(upper.charAt(end));
                if (before && after) {
                    return i;
                }
            }
        }
        return -1;
    }

    private static int matchingParen(String text, int open) {
        int depth = 0;
        boolean inString = false;
        for (int i = open; i < text.length(); i++) {
            char c = text.charAt(i);
            if (inString) {
                if (c == '\'') {
                    if (i + 1 < text.length() && text.charAt(i + 1) == '\'') {
                        i++;
                    } else {
                        inString = false;
                    }
                }
                continue;
            }
            if (c == '\'') {
                inString = true;
            } else if (c == '(') {
                depth++;
            } else if (c == ')') {
                depth--;
                if (depth == 0) {
                    return i;
                }
            }
        }
        throw new IllegalArgumentException("unbalanced parentheses in <" + text + ">");
    }

    private static int indexOfWhitespace(String text) {
        for (int i = 0; i < text.length(); i++) {
            if (Character.isWhitespace(text.charAt(i))) {
                return i;
            }
        }
        return -1;
    }

    private static int parseInt(String text, int defaultValue) {
        try {
            return Integer.parseInt(text);
        } catch (RuntimeException ignore) {
            return defaultValue;
        }
    }

    /** Convenience for tests and diagnostics. */
    static Map<String, Object> row(Object... keyValues) {
        Map<String, Object> row = new HashMap<String, Object>();
        for (int i = 0; i + 1 < keyValues.length; i += 2) {
            row.put(String.valueOf(keyValues[i]), keyValues[i + 1]);
        }
        return row;
    }
}
